# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: makeapp - random notes
email: yanniswithoutthesefourwords@ych.gr
description: > # this means to ignore newlines until "baseurl:"
 make app : build failed. This a collection of random thoughts and notes, mostly around code development, psycology, literature and movies, health and anything else that (core-)dumps out of my mind. If you need someone to blame, check out the About page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ych.gr" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  haritak

# Build settings
markdown: kramdown
